In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("HARtrain.csv")

In [3]:
df

tBodyAcc-mean()-X  tBodyAcc-mean()-X.1  tBodyAcc-mean()-X.2  \
0              0.288585            -0.020294            -0.132905   
1              0.278419            -0.016411            -0.123520   
2              0.279653            -0.019467            -0.113462   
3              0.279174            -0.026201            -0.123283   
4              0.276629            -0.016570            -0.115362   
...                 ...                  ...                  ...   
7347           0.299665            -0.057193            -0.181233   
7348           0.273853            -0.007749            -0.147468   
7349           0.273387            -0.017011            -0.045022   
7350           0.289654            -0.018843            -0.158281   
7351           0.351503            -0.012423            -0.203867   

      tBodyAcc-mean()-X.3  tBodyAcc-mean()-X.4  tBodyAcc-mean()-X.5  \
0               -0.995279            -0.983111            -0.913526   
1               -0.998245            -0.975300            -0.960322   
2               -0.995380            -0.967187            -0.978944   
3               -0.996091            -0.983403            -0.990675   
4               -0.998139            -0.980817            -0.990482   
...                   ...                  ...                  ...   
7347            -0.195387             0.039905             0.077078   
7348            -0.235309             0.004816             0.059280   
7349            -0.218218            -0.103822             0.274533   
7350            -0.219139            -0.111412             0.268893   
7351            -0.269270            -0.087212             0.177404   

      tBodyAcc-mean()-X.6  tBodyAcc-mean()-X.7  tBodyAcc-mean()-X.8  \
0               -0.995112            -0.983185            -0.923527   
1               -0.998807            -0.974914            -0.957686   
2               -0.996520            -0.963668            -0.977469   
3               -0.997099            -0.982750            -0.989302   
4               -0.998321            -0.979672            -0.990441   
...                   ...                  ...                  ...   
7347            -0.282301             0.043616             0.060410   
7348            -0.322552            -0.029456             0.080585   
7349            -0.304515            -0.098913             0.332584   
7350            -0.310487            -0.068200             0.319473   
7351            -0.377404            -0.038678             0.229430   

      tBodyAcc-mean()-X.9  ...  tBodyAcc-mean()-X.553  tBodyAcc-mean()-X.554  \
0               -0.934724  ...              -0.710304              -0.112754   
1               -0.943068  ...              -0.861499               0.053477   
2               -0.938692  ...              -0.760104              -0.118559   
3               -0.938692  ...              -0.482845              -0.036788   
4               -0.942469  ...              -0.699205               0.123320   
...                   ...  ...                    ...                    ...   
7347             0.210795  ...              -0.880324              -0.190437   
7348             0.117440  ...              -0.680744               0.064907   
7349             0.043999  ...              -0.304029               0.052806   
7350             0.101702  ...              -0.344314              -0.101360   
7351             0.269013  ...              -0.740738              -0.280088   

      tBodyAcc-mean()-X.555  tBodyAcc-mean()-X.556  tBodyAcc-mean()-X.557  \
0                  0.030400              -0.464761              -0.018446   
1                 -0.007435              -0.732626               0.703511   
2                  0.177899               0.100699               0.808529   
3                 -0.012892               0.640011              -0.485366   
4                  0.122542               0.693578              -0.615971   
...                     ...                    .

In [4]:
df.shape

(7352, 563)

In [5]:
df.isnull().sum().sum()

0

In [6]:
df.corr()

tBodyAcc-mean()-X  tBodyAcc-mean()-X.1  \
tBodyAcc-mean()-X               1.000000             0.148061   
tBodyAcc-mean()-X.1             0.148061             1.000000   
tBodyAcc-mean()-X.2            -0.256952            -0.078769   
tBodyAcc-mean()-X.3             0.000619            -0.045160   
tBodyAcc-mean()-X.4            -0.021903            -0.044920   
...                                  ...                  ...   
tBodyAcc-mean()-X.557           0.028844             0.075679   
tBodyAcc-mean()-X.558          -0.035257            -0.005309   
tBodyAcc-mean()-X.559           0.034371             0.001053   
tBodyAcc-mean()-X.560           0.028242            -0.013903   
tBodyAcc-mean()-X.561           0.024181            -0.003144   

                       tBodyAcc-mean()-X.2  tBodyAcc-mean()-X.3  \
tBodyAcc-mean()-X                -0.256952             0.000619   
tBodyAcc-mean()-X.1              -0.078769            -0.045160   
tBodyAcc-mean()-X.2               1.000000            -0.020217   
tBodyAcc-mean()-X.3              -0.020217             1.000000   
tBodyAcc-mean()-X.4              -0.016641             0.927461   
...                                    ...                  ...   
tBodyAcc-mean()-X.557            -0.034037            -0.024810   
tBodyAcc-mean()-X.558             0.008587            -0.371653   
tBodyAcc-mean()-X.559            -0.015288             0.471065   
tBodyAcc-mean()-X.560            -0.022643             0.394825   
tBodyAcc-mean()-X.561            -0.000637            -0.064345   

                       tBodyAcc-mean()-X.4  tBodyAcc-mean()-X.5  \
tBodyAcc-mean()-X                -0.021903            -0.044617   
tBodyAcc-mean()-X.1              -0.044920            -0.049746   
tBodyAcc-mean()-X.2              -0.016641            -0.008410   
tBodyAcc-mean()-X.3               0.927461             0.851668   
tBodyAcc-mean()-X.4               1.000000             0.895510   
...                                    ...                  ...   
tBodyAcc-mean()-X.557            -0.014592            -0.006471   
tBodyAcc-mean()-X.558            -0.380531            -0.345011   
tBodyAcc-mean()-X.559             0.523600             0.476006   
tBodyAcc-mean()-X.560             0.433169             0.482828   
tBodyAcc-mean()-X.561            -0.115524            -0.050123   

                       tBodyAcc-mean()-X.6  tBodyAcc-mean()-X.7  \
tBodyAcc-mean()-X                 0.006290            -0.022754   
tBodyAcc-mean()-X.1              -0.044180            -0.045049   
tBodyAcc-mean()-X.2              -0.018747            -0.015203   
tBodyAcc-mean()-X.3               0.998632             0.920888   
tBodyAcc-mean()-X.4               0.922803             0.997347   
...                                    ...                  ...   
tBodyAcc-mean()-X.557            -0.024951            -0.012341   
tBodyAcc-mean()-X.558            -0.368191            -0.377025   
tBodyAcc-mean()-X.559             0.466424             0.525081   
tBodyAcc-mean()-X.560             0.390922             0.431459   
tBodyAcc-mean()-X.561            -0.063440            -0.114753   

                       tBodyAcc-mean()-X.8  tBodyAcc-mean()-X.9  ...  \
tBodyAcc-mean()-X                -0.047558             0.044062  ...   
tBodyAcc-mean()-X.1              -0.050402            -0.038108  ...   
tBodyAcc-mean()-X.2              -0.001988            -0.037197  ...   
tBodyAcc-mean()-X.3               0.846392             0.980844  ...   
tBodyAcc-mean()-X.4               0.894509             0.917366  ...   
...                                    ...                  ...  ...   
tBodyAcc-mean()-X.557            -0.007231            -0.028871  ...   
tBodyAcc-mean()-X.558            -0.347389            -0.384192  ...   
tBodyAcc-mean()-X.559             0.477607             0.480229  ...   
tBodyAcc-mean()-X.560             0.479751             0.405023  ...   
tBodyAcc-mean()-X.561            -0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7352 entries, 0 to 7351
Columns: 563 entries, tBodyAcc-mean()-X to tBodyAcc-mean()-X.562
dtypes: float64(561), int64(1), object(1)
memory usage: 31.6+ MB


In [8]:
df.describe()

tBodyAcc-mean()-X  tBodyAcc-mean()-X.1  tBodyAcc-mean()-X.2  \
count        7352.000000          7352.000000          7352.000000   
mean            0.274488            -0.017695            -0.109141   
std             0.070261             0.040811             0.056635   
min            -1.000000            -1.000000            -1.000000   
25%             0.262975            -0.024863            -0.120993   
50%             0.277193            -0.017219            -0.108676   
75%             0.288461            -0.010783            -0.097794   
max             1.000000             1.000000             1.000000   

       tBodyAcc-mean()-X.3  tBodyAcc-mean()-X.4  tBodyAcc-mean()-X.5  \
count          7352.000000          7352.000000          7352.000000   
mean             -0.605438            -0.510938            -0.604754   
std               0.448734             0.502645             0.418687   
min              -1.000000            -0.999873            -1.000000   
25%              -0.992754            -0.978129            -0.980233   
50%              -0.946196            -0.851897            -0.859365   
75%              -0.242813            -0.034231            -0.262415   
max               1.000000             0.916238             1.000000   

       tBodyAcc-mean()-X.6  tBodyAcc-mean()-X.7  tBodyAcc-mean()-X.8  \
count          7352.000000          7352.000000          7352.000000   
mean             -0.630512            -0.526907            -0.606150   
std               0.424073             0.485942             0.414122   
min              -1.000000            -1.000000            -1.000000   
25%              -0.993591            -0.978162            -0.980251   
50%              -0.950709            -0.857328            -0.857143   
75%              -0.292680            -0.066701            -0.265671   
max               1.000000             0.967664             1.000000   

       tBodyAcc-mean()-X.9  ...  tBodyAcc-mean()-X.552  tBodyAcc-mean()-X.553  \
count          7352.000000  ...            7352.000000            7352.000000   
mean             -0.468604  ...              -0.307009              -0.625294   
std               0.544547  ...               0.321011               0.307584   
min              -1.000000  ...              -0.995357              -0.999765   
25%              -0.936219  ...              -0.542602              -0.845573   
50%              -0.881637  ...              -0.343685              -0.711692   
75%              -0.017129  ...              -0.126979              -0.503878   
max               1.000000  ...               0.989538               0.956845   

       tBodyAcc-mean()-X.554  tBodyAcc-mean()-X.555  tBodyAcc-mean()-X.556  \
count            7352.000000            7352.000000            7352.000000   
mean                0.008684               0.002186               0.008726   
std                 0.336787               0.448306               0.608303   
min                -0.976580              -1.000000              -1.000000   
25%                -0.121527              -0.289549              -0.482273   
50%                 0.009509               0.008943               0.008735   
75%                 0.150865               0.292861               0.506187   
max                 1.000000               1.000000               0.998702   

       tBodyAcc-mean()-X.557  tBodyAcc-mean()-X.558  tBodyAcc-mean()-X.559  \
count            7352.000000            7352.000000            7352.000000   
mean               -0.005981              -0.489547               0.058593   
std                 0.477975               0.511807               0.297480   
min                -1.000000              -1.000000              -1.000000   
25%                -0.376341              -0.812065              -0.017885   
50%                -0.000368              -0.709417               0.182071   
75%                 0.359368              -0.509079               0.248353   
max                 0

In [9]:
df['tBodyAcc-mean()-X.562'].unique()

array(['STANDING', 'SITTING', 'LAYING', 'WALKING', 'WALKING_DOWNSTAIRS',
       'WALKING_UPSTAIRS'], dtype=object)

In [10]:
df['tBodyAcc-mean()-X.562'].replace({'STANDING':1, 'SITTING':2, 'LAYING':3, 'WALKING':4, 'WALKING_DOWNSTAIRS':6,
       'WALKING_UPSTAIRS':7},inplace=True)

In [11]:
df

tBodyAcc-mean()-X  tBodyAcc-mean()-X.1  tBodyAcc-mean()-X.2  \
0              0.288585            -0.020294            -0.132905   
1              0.278419            -0.016411            -0.123520   
2              0.279653            -0.019467            -0.113462   
3              0.279174            -0.026201            -0.123283   
4              0.276629            -0.016570            -0.115362   
...                 ...                  ...                  ...   
7347           0.299665            -0.057193            -0.181233   
7348           0.273853            -0.007749            -0.147468   
7349           0.273387            -0.017011            -0.045022   
7350           0.289654            -0.018843            -0.158281   
7351           0.351503            -0.012423            -0.203867   

      tBodyAcc-mean()-X.3  tBodyAcc-mean()-X.4  tBodyAcc-mean()-X.5  \
0               -0.995279            -0.983111            -0.913526   
1               -0.998245            -0.975300            -0.960322   
2               -0.995380            -0.967187            -0.978944   
3               -0.996091            -0.983403            -0.990675   
4               -0.998139            -0.980817            -0.990482   
...                   ...                  ...                  ...   
7347            -0.195387             0.039905             0.077078   
7348            -0.235309             0.004816             0.059280   
7349            -0.218218            -0.103822             0.274533   
7350            -0.219139            -0.111412             0.268893   
7351            -0.269270            -0.087212             0.177404   

      tBodyAcc-mean()-X.6  tBodyAcc-mean()-X.7  tBodyAcc-mean()-X.8  \
0               -0.995112            -0.983185            -0.923527   
1               -0.998807            -0.974914            -0.957686   
2               -0.996520            -0.963668            -0.977469   
3               -0.997099            -0.982750            -0.989302   
4               -0.998321            -0.979672            -0.990441   
...                   ...                  ...                  ...   
7347            -0.282301             0.043616             0.060410   
7348            -0.322552            -0.029456             0.080585   
7349            -0.304515            -0.098913             0.332584   
7350            -0.310487            -0.068200             0.319473   
7351            -0.377404            -0.038678             0.229430   

      tBodyAcc-mean()-X.9  ...  tBodyAcc-mean()-X.553  tBodyAcc-mean()-X.554  \
0               -0.934724  ...              -0.710304              -0.112754   
1               -0.943068  ...              -0.861499               0.053477   
2               -0.938692  ...              -0.760104              -0.118559   
3               -0.938692  ...              -0.482845              -0.036788   
4               -0.942469  ...              -0.699205               0.123320   
...                   ...  ...                    ...                    ...   
7347             0.210795  ...              -0.880324              -0.190437   
7348             0.117440  ...              -0.680744               0.064907   
7349             0.043999  ...              -0.304029               0.052806   
7350             0.101702  ...              -0.344314              -0.101360   
7351             0.269013  ...              -0.740738              -0.280088   

      tBodyAcc-mean()-X.555  tBodyAcc-mean()-X.556  tBodyAcc-mean()-X.557  \
0                  0.030400              -0.464761              -0.018446   
1                 -0.007435              -0.732626               0.703511   
2                  0.177899               0.100699               0.808529   
3                 -0.012892               0.640011              -0.485366   
4                  0.122542               0.693578              -0.615971   
...                     ...                    .

# Exploratory Data Analysis

In [12]:
Numerical_features=[feature for feature in df.columns if df[feature].dtype!='O']

In [13]:
len(Numerical_features)#so all features are numerical in the data except last columns i.e.,activities

563

In [14]:
X=df.iloc[:,:562]

In [15]:
X

tBodyAcc-mean()-X  tBodyAcc-mean()-X.1  tBodyAcc-mean()-X.2  \
0              0.288585            -0.020294            -0.132905   
1              0.278419            -0.016411            -0.123520   
2              0.279653            -0.019467            -0.113462   
3              0.279174            -0.026201            -0.123283   
4              0.276629            -0.016570            -0.115362   
...                 ...                  ...                  ...   
7347           0.299665            -0.057193            -0.181233   
7348           0.273853            -0.007749            -0.147468   
7349           0.273387            -0.017011            -0.045022   
7350           0.289654            -0.018843            -0.158281   
7351           0.351503            -0.012423            -0.203867   

      tBodyAcc-mean()-X.3  tBodyAcc-mean()-X.4  tBodyAcc-mean()-X.5  \
0               -0.995279            -0.983111            -0.913526   
1               -0.998245            -0.975300            -0.960322   
2               -0.995380            -0.967187            -0.978944   
3               -0.996091            -0.983403            -0.990675   
4               -0.998139            -0.980817            -0.990482   
...                   ...                  ...                  ...   
7347            -0.195387             0.039905             0.077078   
7348            -0.235309             0.004816             0.059280   
7349            -0.218218            -0.103822             0.274533   
7350            -0.219139            -0.111412             0.268893   
7351            -0.269270            -0.087212             0.177404   

      tBodyAcc-mean()-X.6  tBodyAcc-mean()-X.7  tBodyAcc-mean()-X.8  \
0               -0.995112            -0.983185            -0.923527   
1               -0.998807            -0.974914            -0.957686   
2               -0.996520            -0.963668            -0.977469   
3               -0.997099            -0.982750            -0.989302   
4               -0.998321            -0.979672            -0.990441   
...                   ...                  ...                  ...   
7347            -0.282301             0.043616             0.060410   
7348            -0.322552            -0.029456             0.080585   
7349            -0.304515            -0.098913             0.332584   
7350            -0.310487            -0.068200             0.319473   
7351            -0.377404            -0.038678             0.229430   

      tBodyAcc-mean()-X.9  ...  tBodyAcc-mean()-X.552  tBodyAcc-mean()-X.553  \
0               -0.934724  ...              -0.298676              -0.710304   
1               -0.943068  ...              -0.595051              -0.861499   
2               -0.938692  ...              -0.390748              -0.760104   
3               -0.938692  ...              -0.117290              -0.482845   
4               -0.942469  ...              -0.351471              -0.699205   
...                   ...  ...                    ...                    ...   
7347             0.210795  ...              -0.588433              -0.880324   
7348             0.117440  ...              -0.390738              -0.680744   
7349             0.043999  ...               0.025145              -0.304029   
7350             0.101702  ...               0.063907              -0.344314   
7351             0.269013  ...              -0.387052              -0.740738   

      tBodyAcc-mean()-X.554  tBodyAcc-mean()-X.555  tBodyAcc-mean()-X.556  \
0                 -0.112754               0.030400              -0.464761   
1                  0.053477              -0.007435              -0.732626   
2                 -0.118559               0.177899               0.100699   
3                 -0.036788              -0.012892               0.640011   
4                  0.123320               0.122542               0.693578   
...                     ...                    .

In [16]:
y=pd.DataFrame(df.iloc[:,-1])

In [17]:
y

tBodyAcc-mean()-X.562
0                         1
1                         1
2                         1
3                         1
4                         1
...                     ...
7347                      7
7348                      7
7349                      7
7350                      7
7351                      7

[7352 rows x 1 columns]

# Training the model

In [18]:
from sklearn.model_selection import train_test_split

In [19]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [20]:
print(X_train.shape,y_train.shape,X_test.shape,y_test.shape)

(5881, 562) (5881, 1) (1471, 562) (1471, 1)


In [21]:
from sklearn.ensemble import RandomForestClassifier

In [22]:
rf=RandomForestClassifier()

In [23]:
rf.fit(X_train,y_train)

C:\Users\wwwka\AppData\Local\Temp/ipykernel_7320/1593328843.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train,y_train)


RandomForestClassifier()

In [24]:
rf.score(X_train,y_train)

1.0

In [25]:
rf.score(X_test,y_test)

0.981645139360979

In [26]:
y_pred=rf.predict(X_test)

In [27]:
y_pred

array([3, 1, 6, ..., 3, 2, 2], dtype=int64)

In [28]:
from sklearn.linear_model import LogisticRegression

In [29]:
lr=LogisticRegression()

In [30]:
lr.fit(X_train,y_train)

C:\Users\wwwka\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)
C:\Users\wwwka\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [31]:
lr.score(X_train,y_train)

0.9897976534602959

In [32]:
lr.score(X_test,y_test)

0.9782460910944936

In [33]:
from sklearn.linear_model import LinearRegression
lrg=LinearRegression()

In [34]:
lrg.fit(X_train,y_train)

LinearRegression()

In [35]:
lrg.score(X_train,y_train)

0.9704947514802843

In [36]:
lrg.score(X_test,y_test)

0.961400698007632

In [37]:
from sklearn.metrics import confusion_matrix,classification_report

In [38]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           1       0.98      0.95      0.96       286
           2       0.95      0.98      0.96       267
           3       1.00      1.00      1.00       285
           4       0.98      0.99      0.99       242
           6       0.98      1.00      0.99       193
           7       1.00      0.97      0.99       198

    accuracy                           0.98      1471
   macro avg       0.98      0.98      0.98      1471
weighted avg       0.98      0.98      0.98      1471



In [39]:
pred=lrg.predict(X_test)

In [41]:
print(confusion_matrix(y_pred,y_test))

[[272  14   0   0   0   0]
 [  6 261   0   0   0   0]
 [  0   0 285   0   0   0]
 [  0   0   0 240   2   0]
 [  0   0   0   0 193   0]
 [  0   0   0   4   1 193]]


In [44]:
from sklearn.tree import DecisionTreeClassifier

In [50]:
dt=DecisionTreeClassifier()

In [51]:
dt.fit(X_train,y_train)

DecisionTreeClassifier()

In [52]:
dt.score(X_train,y_train)

1.0

In [53]:
dt.score(X_test,y_test)

0.9340584636301835

In [54]:
pred1=dt.predict(X_test)

In [63]:
print(classification_report(pred1,y_test))

              precision    recall  f1-score   support

           1       0.92      0.92      0.92       278
           2       0.92      0.92      0.92       275
           3       1.00      1.00      1.00       285
           4       0.95      0.91      0.93       254
           6       0.91      0.93      0.92       193
           7       0.87      0.90      0.88       186

    accuracy                           0.93      1471
   macro avg       0.93      0.93      0.93      1471
weighted avg       0.93      0.93      0.93      1471

